### ISSUE TITLE
New Challenge

### ISSUE THREAD

**Issue by andress134** [ElementumOrg/cfbypass#1]
Hello, do u offer updates for new challenge ?

**Comment by elgatito** [comment]
@andress134 as far as I understand, there are no solutions to bypass latest CloudFlare challenge. They changed it a lot.

**Comment by andress134** [comment]
> @andress134 as far as I understand, there are no solutions to bypass latest CloudFlare challenge. They changed it a lot.

yes i know, but i think some lib still can bypass, like cloudscraper (python vers)
https://github.com/scaredos/cfresearch here are all cf changes

**Comment by elgatito** [comment]
I am not planning doing changes in this library, so anybody can fork and try to improve, looking at any working project.
